### ISSUE TITLE
Spritesheet texture path must be quoted in .spt file

### ISSUE THREAD

**Issue by JonnyPtn** [fallahn/xygine#66]
I haven't had a chance to investigate yet, just noting this down as it's caught me out a few times and I don't want to forget:

If the src parameter in the sprite file doesn't have quotes it will not load the texture correctly, e.g:

- `src=some/path.png` doesn't work
- `src = "some/path.png"` does work

**Comment by fallahn** [comment]
Yup, that's how the parser knows it's a string (and not a number or array of numbers) - although this isn't really documented anywhere. If it feels counter intuitive I'm open to suggestions :)

**Comment by JonnyPtn** [comment]
It does seem a bit odd as you specify the type (std::string) as a template parameter, so I'd expect it to try and parse as whatever type I've requested.

Maybe the parser just needs a bit of smartening up at some point in the future, I'm sure there's some regex or similar magic which can be done for that

**Comment by fallahn** [comment]
On closer inspection it also deals with strings which have spaces in them, which would otherwise confound the parser. Perhaps the best solution would be to make the quotes optional, except for strings with spaces in them where the quotes would be necessary. This would at least cause it to behave like pretty much any CLI/Terminal

**Comment by fallahn** [comment]
let me know if this improves the situation :)

**Comment by JonnyPtn** [comment]
Looks good to me!
